// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3hXHfi4RWDxX6WRkSSBk_RTwYeFDYy_g',
    appId: '1:906286135972:web:cfc1a690d5697f56e2c431',
    messagingSenderId: '906286135972',
    projectId: 'flutter-project-9e072',
    authDomain: 'flutter-project-9e072.firebaseapp.com',
    storageBucket: 'flutter-project-9e072.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADh6s4I8gmidautI-m1IrK6wV44qUdn2Q',
    appId: '1:906286135972:android:20c8d8dcb4df135ce2c431',
    messagingSenderId: '906286135972',
    projectId: 'flutter-project-9e072',
    storageBucket: 'flutter-project-9e072.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABepuj6ngRoBJruim5pjG-cLB0mvx-D_w',
    appId: '1:906286135972:ios:0dae7916ab197328e2c431',
    messagingSenderId: '906286135972',
    projectId: 'flutter-project-9e072',
    storageBucket: 'flutter-project-9e072.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABepuj6ngRoBJruim5pjG-cLB0mvx-D_w',
    appId: '1:906286135972:ios:0dae7916ab197328e2c431',
    messagingSenderId: '906286135972',
    projectId: 'flutter-project-9e072',
    storageBucket: 'flutter-project-9e072.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxFORJ6nkDx-Evfq2NbPlHfx799MZy3qE',
    appId: '1:906286135972:web:efd06dcd3562402ae2c431',
    messagingSenderId: '906286135972',
    projectId: 'flutter-project-9e072',
    authDomain: 'flutter-project-9e072.firebaseapp.com',
    storageBucket: 'flutter-project-9e072.firebasestorage.app',
  );
}
